import { cn } from "~/lib/utils";

export function LoaderGridStars({
  className,
  ...props
}: React.ComponentProps<"svg">) {
  return (
    <svg
      width="16"
      height="16"
      fill="none"
      viewBox="0 0 16 16"
      xmlns="http://www.w3.org/2000/svg"
      className={cn("loader-grid-stars", className)}
      {...props}
    >
      <circle
        className="grid-dot-0-0-star"
        cx="1"
        cy="1"
        r="1"
        fill="currentColor"
        opacity="var(--opacity-grid-dot-0-0-star)"
      ></circle>
      <circle
        className="grid-dot-0-1-star"
        cx="4.5"
        cy="1"
        r="1"
        fill="currentColor"
        opacity="var(--opacity-grid-dot-0-1-star)"
      ></circle>
      <circle
        className="grid-dot-0-2-star"
        cx="8"
        cy="1"
        r="1"
        fill="currentColor"
        opacity="var(--opacity-grid-dot-0-2-star)"
      ></circle>
      <circle
        className="grid-dot-0-3-star"
        cx="11.5"
        cy="1"
        r="1"
        fill="currentColor"
        opacity="var(--opacity-grid-dot-0-3-star)"
      ></circle>
      <circle
        className="grid-dot-0-4-star"
        cx="15"
        cy="1"
        r="1"
        fill="currentColor"
        opacity="var(--opacity-grid-dot-0-4-star)"
      ></circle>
      <circle
        className="grid-dot-1-0-star"
        cx="1"
        cy="4.5"
        r="1"
        fill="currentColor"
        opacity="var(--opacity-grid-dot-1-0-star)"
      ></circle>
      <circle
        className="grid-dot-1-1-star"
        cx="4.5"
        cy="4.5"
        r="1"
        fill="currentColor"
        opacity="var(--opacity-grid-dot-1-1-star)"
      ></circle>
      <circle
        className="grid-dot-1-2-star"
        cx="8"
        cy="4.5"
        r="1"
        fill="currentColor"
        opacity="var(--opacity-grid-dot-1-2-star)"
      ></circle>
      <circle
        className="grid-dot-1-3-star"
        cx="11.5"
        cy="4.5"
        r="1"
        fill="currentColor"
        opacity="var(--opacity-grid-dot-1-3-star)"
      ></circle>
      <circle
        className="grid-dot-1-4-star"
        cx="15"
        cy="4.5"
        r="1"
        fill="currentColor"
        opacity="var(--opacity-grid-dot-1-4-star)"
      ></circle>
      <circle
        className="grid-dot-2-0-star"
        cx="1"
        cy="8"
        r="1"
        fill="currentColor"
        opacity="var(--opacity-grid-dot-2-0-star)"
      ></circle>
      <circle
        className="grid-dot-2-1-star"
        cx="4.5"
        cy="8"
        r="1"
        fill="currentColor"
        opacity="var(--opacity-grid-dot-2-1-star)"
      ></circle>
      <circle
        className="grid-dot-2-2-star"
        cx="8"
        cy="8"
        r="1"
        fill="currentColor"
        opacity="var(--opacity-grid-dot-2-2-star)"
      ></circle>
      <circle
        className="grid-dot-2-3-star"
        cx="11.5"
        cy="8"
        r="1"
        fill="currentColor"
        opacity="var(--opacity-grid-dot-2-3-star)"
      ></circle>
      <circle
        className="grid-dot-2-4-star"
        cx="15"
        cy="8"
        r="1"
        fill="currentColor"
        opacity="var(--opacity-grid-dot-2-4-star)"
      ></circle>
      <circle
        className="grid-dot-3-0-star"
        cx="1"
        cy="11.5"
        r="1"
        fill="currentColor"
        opacity="var(--opacity-grid-dot-3-0-star)"
      ></circle>
      <circle
        className="grid-dot-3-1-star"
        cx="4.5"
        cy="11.5"
        r="1"
        fill="currentColor"
        opacity="var(--opacity-grid-dot-3-1-star)"
      ></circle>
      <circle
        className="grid-dot-3-2-star"
        cx="8"
        cy="11.5"
        r="1"
        fill="currentColor"
        opacity="var(--opacity-grid-dot-3-2-star)"
      ></circle>
      <circle
        className="grid-dot-3-3-star"
        cx="11.5"
        cy="11.5"
        r="1"
        fill="currentColor"
        opacity="var(--opacity-grid-dot-3-3-star)"
      ></circle>
      <circle
        className="grid-dot-3-4-star"
        cx="15"
        cy="11.5"
        r="1"
        fill="currentColor"
        opacity="var(--opacity-grid-dot-3-4-star)"
      ></circle>
      <circle
        className="grid-dot-4-0-star"
        cx="1"
        cy="15"
        r="1"
        fill="currentColor"
        opacity="var(--opacity-grid-dot-4-0-star)"
      ></circle>
      <circle
        className="grid-dot-4-1-star"
        cx="4.5"
        cy="15"
        r="1"
        fill="currentColor"
        opacity="var(--opacity-grid-dot-4-1-star)"
      ></circle>
      <circle
        className="grid-dot-4-2-star"
        cx="8"
        cy="15"
        r="1"
        fill="currentColor"
        opacity="var(--opacity-grid-dot-4-2-star)"
      ></circle>
      <circle
        className="grid-dot-4-3-star"
        cx="11.5"
        cy="15"
        r="1"
        fill="currentColor"
        opacity="var(--opacity-grid-dot-4-3-star)"
      ></circle>
      <circle
        className="grid-dot-4-4-star"
        cx="15"
        cy="15"
        r="1"
        fill="currentColor"
        opacity="var(--opacity-grid-dot-4-4-star)"
      ></circle>
    </svg>
  );
}
