import { cn } from "~/lib/utils";

export function LoaderGridPingPong({
  className,
  ...props
}: React.ComponentProps<"svg">) {
  return (
    <svg
      width="16"
      height="16"
      fill="none"
      viewBox="0 0 16 16"
      xmlns="http://www.w3.org/2000/svg"
      className={cn("loader-grid-ping-pong", className)}
      {...props}
    >
      <circle
        className="grid-dot-0-0-pong"
        cx="1"
        cy="1"
        r="1"
        fill="currentColor"
        opacity="var(--opacity-grid-dot-0-0-pong)"
      ></circle>
      <circle
        className="grid-dot-0-1-pong"
        cx="4.5"
        cy="1"
        r="1"
        fill="currentColor"
        opacity="var(--opacity-grid-dot-0-1-pong)"
      ></circle>
      <circle
        className="grid-dot-0-2-pong"
        cx="8"
        cy="1"
        r="1"
        fill="currentColor"
        opacity="var(--opacity-grid-dot-0-2-pong)"
      ></circle>
      <circle
        className="grid-dot-0-3-pong"
        cx="11.5"
        cy="1"
        r="1"
        fill="currentColor"
        opacity="var(--opacity-grid-dot-0-3-pong)"
      ></circle>
      <circle
        className="grid-dot-0-4-pong"
        cx="15"
        cy="1"
        r="1"
        fill="currentColor"
        opacity="var(--opacity-grid-dot-0-4-pong)"
      ></circle>
      <circle
        className="grid-dot-1-0-pong"
        cx="1"
        cy="4.5"
        r="1"
        fill="currentColor"
        opacity="var(--opacity-grid-dot-1-0-pong)"
      ></circle>
      <circle
        className="grid-dot-1-1-pong"
        cx="4.5"
        cy="4.5"
        r="1"
        fill="currentColor"
        opacity="var(--opacity-grid-dot-1-1-pong)"
      ></circle>
      <circle
        className="grid-dot-1-2-pong"
        cx="8"
        cy="4.5"
        r="1"
        fill="currentColor"
        opacity="var(--opacity-grid-dot-1-2-pong)"
      ></circle>
      <circle
        className="grid-dot-1-3-pong"
        cx="11.5"
        cy="4.5"
        r="1"
        fill="currentColor"
        opacity="var(--opacity-grid-dot-1-3-pong)"
      ></circle>
      <circle
        className="grid-dot-1-4-pong"
        cx="15"
        cy="4.5"
        r="1"
        fill="currentColor"
        opacity="var(--opacity-grid-dot-1-4-pong)"
      ></circle>
      <circle
        className="grid-dot-2-0-pong"
        cx="1"
        cy="8"
        r="1"
        fill="currentColor"
        opacity="var(--opacity-grid-dot-2-0-pong)"
      ></circle>
      <circle
        className="grid-dot-2-1-pong"
        cx="4.5"
        cy="8"
        r="1"
        fill="currentColor"
        opacity="var(--opacity-grid-dot-2-1-pong)"
      ></circle>
      <circle
        className="grid-dot-2-2-pong"
        cx="8"
        cy="8"
        r="1"
        fill="currentColor"
        opacity="var(--opacity-grid-dot-2-2-pong)"
      ></circle>
      <circle
        className="grid-dot-2-3-pong"
        cx="11.5"
        cy="8"
        r="1"
        fill="currentColor"
        opacity="var(--opacity-grid-dot-2-3-pong)"
      ></circle>
      <circle
        className="grid-dot-2-4-pong"
        cx="15"
        cy="8"
        r="1"
        fill="currentColor"
        opacity="var(--opacity-grid-dot-2-4-pong)"
      ></circle>
      <circle
        className="grid-dot-3-0-pong"
        cx="1"
        cy="11.5"
        r="1"
        fill="currentColor"
        opacity="var(--opacity-grid-dot-3-0-pong)"
      ></circle>
      <circle
        className="grid-dot-3-1-pong"
        cx="4.5"
        cy="11.5"
        r="1"
        fill="currentColor"
        opacity="var(--opacity-grid-dot-3-1-pong)"
      ></circle>
      <circle
        className="grid-dot-3-2-pong"
        cx="8"
        cy="11.5"
        r="1"
        fill="currentColor"
        opacity="var(--opacity-grid-dot-3-2-pong)"
      ></circle>
      <circle
        className="grid-dot-3-3-pong"
        cx="11.5"
        cy="11.5"
        r="1"
        fill="currentColor"
        opacity="var(--opacity-grid-dot-3-3-pong)"
      ></circle>
      <circle
        className="grid-dot-3-4-pong"
        cx="15"
        cy="11.5"
        r="1"
        fill="currentColor"
        opacity="var(--opacity-grid-dot-3-4-pong)"
      ></circle>
      <circle
        className="grid-dot-4-0-pong"
        cx="1"
        cy="15"
        r="1"
        fill="currentColor"
        opacity="var(--opacity-grid-dot-4-0-pong)"
      ></circle>
      <circle
        className="grid-dot-4-1-pong"
        cx="4.5"
        cy="15"
        r="1"
        fill="currentColor"
        opacity="var(--opacity-grid-dot-4-1-pong)"
      ></circle>
      <circle
        className="grid-dot-4-2-pong"
        cx="8"
        cy="15"
        r="1"
        fill="currentColor"
        opacity="var(--opacity-grid-dot-4-2-pong)"
      ></circle>
      <circle
        className="grid-dot-4-3-pong"
        cx="11.5"
        cy="15"
        r="1"
        fill="currentColor"
        opacity="var(--opacity-grid-dot-4-3-pong)"
      ></circle>
      <circle
        className="grid-dot-4-4-pong"
        cx="15"
        cy="15"
        r="1"
        fill="currentColor"
        opacity="var(--opacity-grid-dot-4-4-pong)"
      ></circle>
    </svg>
  );
}
